spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  application:
    name: LoQueTengo-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false  # importante, lo explicamos abajo
  web:
    error:
      include-message: always
      include-binding-errors: always

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# 🆕 Configuración de JWT
jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}  # Por defecto 60 si no está la env